name: Deploy Site
on: [push]

jobs:
  weblog_import:
    runs-on: ubuntu-latest
    name: lritter.io
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: weblog_import
        uses: neatnik/weblog.lol@v1
        env:
          ADDRESS: lritter
          WEBLOG_API_KEY: ${{ secrets.WEBLOG_API_KEY }}
      - id: post_now
        run: ./script/build-now-payload.sh
